env:
  browser: true
  node: true
  es2021: true
extends:
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures: 
    experimentalObjectRestSpread: true
rules: 
  semi: ["error", "always"],
  quotes: ["error", "double"]
