trailingComma: 'all'
tabWidth: 4
semi: true
singleQuote: true
endOfLine: 'lf'
printWidth: 120
overrides:
    - files: '.prettierrc'
      options:
          parser: 'yaml'
    - files: ['*.md', '*.json', '*.yml', '*.yaml']
      options:
          tabWidth: 2
